### ISSUE TITLE
Unable to start Kestrel

### ISSUE THREAD

**Issue by isaacrlevin** [dotnet-labs/KestrelHttps#1]
When I download your repo and run this command 

> docker-compose up

I get this error

```
api_1  | crit: Microsoft.AspNetCore.Server.Kestrel[0]
api_1  |       Unable to start Kestrel.
api_1  | Interop+Crypto+OpenSslCryptographicException: error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data
api_1  |    at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromBio(SafeBioHandle bio, SafePasswordHandle password)
api_1  |    at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
api_1  |    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
api_1  |    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
api_1  |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
api_1  |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadDefaultCert(ConfigurationReader configReader)
api_1  |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
api_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.ValidateOptions()
api_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
```

I have the latest 3.1 SDK

**Comment by changhuixu** [comment]
Hi @isaacrlevin , 

Thanks for reporting. I realized that my SSL certificate is not uploaded to GitHub. I modified my `.gitignore`. Now the application should be able to start in Docker Compose.

Once it is built by docker, visit [https://localhost:44392/](https://localhost:44392/)
